module.exports = [
  { times: 'regular/times.svg' },
  { code: 'regular/code.svg' },
  { cube: 'regular/cube.svg' },
  { house: 'regular/house.svg' },
  { wrench: 'regular/wrench.svg' },
  { palette: 'regular/palette.svg' },
  { heart: 'regular/heart.svg' },
  { moon: 'solid/moon.svg' },
  { sun: 'solid/sun.svg' },
  { 'chevron-right': 'regular/chevron-right.svg' },
  { 'angle-left': 'regular/angle-left.svg' },
  { 'angle-right': 'regular/angle-right.svg' },
  { 'exclamation-circle': 'solid/exclamation-circle.svg' },
];
